### PR TITLE
Feat/display extrinsic data

### PR DESCRIPTION
**Pull request by remon-nashid**
@BilalAlGhazi I tried to adjust the layout of Signing and Authorization dialogs as much as I could. Can I rely on you to make them match the designs? It was too hellish of a task.

### CODE REVIEW

**Comment by BilalAlGhazi** [comment]
All looks good, but I am unable to test it due to the error above in the dApps

**Comment by remon-nashid** [comment]
@BilalAlGhazi weird, I'll check the polymesh-issuer issue. Meanwhile, you can test extrinsics on `https://polkadot.js.org/apps`, eg Transfer.

**Comment by BilalAlGhazi** [comment]
@remon-nashid for some reason, the wallet account is not showing on https://polkadot.js.org/apps
I am connected to PMF and I got the authorization popup and authorized it

**Comment by remon-nashid** [comment]
> the wallet account is not showing on https://polkadot.js.org/apps
I am connected to PMF and I got the authorization popup and authorized it

I'm going to work in this in a separate PR (WAL-47).

**Review by BilalAlGhazi — APPROVED** [review]

**Pull request merged**
