### PR TITLE
WAL-160: Initial commit of access management

### PR DESCRIPTION
**Pull request by remon-nashid**

### CODE REVIEW

**Comment by wahidrahim** [comment]
Added the following updates:

- allow scrolling only in the website list area
- center "denied"/"allowed" switch labels
- general refactors

Screenshot:

**Review by wahidrahim — APPROVED** [review]
Looks good to me, and works just like it should! Very useful feature 👍

**Comment by remon-nashid** [comment]
Great job @wahidrahim !

**Pull request merged**
