### PR TITLE
feat: ledger hardware wallet troubleshooting instructions

### PR DESCRIPTION
**Pull request by wahidrahim**
Troubleshooting component to display instructions for possible errors when connecting the Ledger hardware wallet. Can add more troubleshooting instructions later based on discovery.

Example: device is not connected/locked —

Example: after connecting and unlocking the device, but the app is not open —

### CODE REVIEW

**Comment by wahidrahim** [comment]
Drafting this PR to make the necessary changes:

- include both instructions
- highlight the appropriate instruction based on error

**Comment by wahidrahim** [comment]
Updated to show everything together, and highlight accordingly. This fits more closely with the original designs:

**Comment by remon-nashid** [comment]
@wahidrahim this looks great! We can merge this as is and gather feedback tomorrow.

**Review by remon-nashid — APPROVED** [review]
Good job @wahidrahim !

**Pull request merged**
