### PR TITLE
[WAL-136] [WAL-137] update wallet balance displays

### PR DESCRIPTION
**Pull request by wahidrahim**
- show available (free to use) balance in account header
- show locked balance in account header
- show total balance in individual account cards
- show available balance as hover text on balance amount, in individual account cards

Screenshot:

### CODE REVIEW

**Comment by remon-nashid** [comment]
@wahidrahim should we put this on hold until we understand core balance lingo better?

**Comment by wahidrahim** [comment]
@remon-nashid sure, I also wouldn't mind running it by Stan regarding design, which will inevitably get updated from this current state.

I am also second guessing showing the full balance (locked + available) in the account cards; doesn't seem intuitive, and it probably should show the available amount instead.

**Comment by remon-nashid** [comment]
@wahidrahim I think the design is fine and either way we go, some users will still find it confusing. 

The only impediment to this PR is fully understand that constitutes "usable" vs "unusable" balance.

**Review by remon-nashid — CHANGES_REQUESTED** [review]
@wahidrahim let's update values based on core provided formulas:

Total = free + reserved
Free = free - miscFrozen
Locked = reserved + miscFrozen

**Comment by wahidrahim** [comment]
Updates:

- made available balance the displayed balance in the account cards (hover shows locked amount)
- added utility function that gives `{ total, available, locked }` balance amounts from (Polkadot's) `AccountData`
- added `balance: { total, available, locked }` property to `AccountData` and `IdentifiedAccount` types
- adjusted UI to better align available and locked balance amounts in the header

**Review by remon-nashid — APPROVED** [review]

**Pull request merged**
