### PR TITLE
[WAL-169] Prevent did alias from being shortened

### PR DESCRIPTION
**Pull request by wahidrahim**
Before:
image

After:
image

### CODE REVIEW

**Review by remon-nashid — CHANGES_REQUESTED** [review]
It appears that identity shortening was put in place to prevent this:

Screen Shot 2021-04-30 at 10 43 23 AM

I guess we need a different shortening logic for strings, that doesn't necessarily aim to keep the first and last few characters of a string. Maybe we can use `text-overflow: ellipsis;` for identity alias.

**Comment by wahidrahim** [comment]
> Maybe we can use `text-overflow: ellipsis;` for identity alias.

@remon-nashid ah I see, yes it will need the same treatment as the account names

**Comment by wahidrahim** [comment]
Updated:
- use `TextOverflowEllipsis` for did alias text
- noticed there is an unnecessary margin-left for did when there is no did alias. Made this margin-left conditional: add only if there is a did alias

Screen Shot 2021-05-03 at 11 07 30

**Review by remon-nashid — APPROVED** [review]

**Pull request merged**
