### PR TITLE
Fix data stagnation issues

### PR DESCRIPTION
**Pull request by remon-nashid**
The issue manifested itself in form of: balance not updating, primary/secondary keys not updating or CDD status not updating. Here's what this PR brings:
- Remove ApiPromise caching and close websocket connection upon popup closing. Also create a new api instance on every connection of Popup.
- Remove the newHeads subscription, in favor of retrieving Did's CDD status on every load.
- Enhance Did/Cdd fetching and storage. No more merging new data into old data.
- Also bump to the latest stable Polkadot dependencies.

### CODE REVIEW

**Comment by remon-nashid** [comment]
@BilalAlGhazi this is ready for review now.

**Comment by remon-nashid** [comment]
Need to do one more change to stop cdd badge from flickering.

**Comment by remon-nashid** [comment]
@wahidrahim Do you mind testing this PR with your day-to-day accounts, to make sure their Did, CDD and Balances are updating correctly?

**Review by BilalAlGhazi — APPROVED** [review]
Great work!

**Pull request merged**
