### PR TITLE
[WAL-177] refactor account restore flow

### PR DESCRIPTION
**Pull request by wahidrahim**
I decided to just use the newer `<Restore />` popup for all seed or JSON type account restoration. However, instead of using an internal component state to determine which tab is selected, I changed it to use route params. This makes it possible to navigate to the seed or JSON-restore tab from anywhere.

In summary:
- use `account/restore/:method` route for all seed/JSON account recovery
- refactor UI and fix spacing issues
- remove previous (now duplicated) components related to seed/JSON account restore

### CODE REVIEW

**Review by remon-nashid — CHANGES_REQUESTED** [review]
@wahidrahim works great but do you mind checking the test error above? seems that route paths are confusing the test.

**Comment by wahidrahim** [comment]
e2e ftw! Should be fixed now

**Review by remon-nashid — APPROVED** [review]
Best PR ever!

Screenshot from 2021-05-10 19-40-50

**Pull request merged**
