### PR TITLE
feat: update account card UI (WAL-122)

### PR DESCRIPTION
**Pull request by wahidrahim**
Demo: https://polymath.atlassian.net/browse/WAL-122?focusedCommentId=15747

✅ Badge should be vertically aligned with balance display as well, while not overlapping with the selection checkmark.

Used CSS grids + flex to define the layouts for account details + hover state for unassigned accounts.

✅ Names should have max width and then elipsises. 

Created a new `TextOverflowEllipsis` component which requires a `maxWidth`; if text inside overflows it will use "..." as the last characters (CSS only).

⛔️ (optional) Preferably, both secondary and primary badged should have the same width.

I thought it looked nice as it is, I experiemented with uniform badge widths, I actually thought the current way is fine/better in comparison. For refernce, this is how it looks with uniform widths:

image

Let me know if I should go ahead with this change!

### CODE REVIEW

**Comment by wahidrahim** [comment]
I just noticed the badges are not perfectly aligned (the primary badge is a bit to the left I think). I'll make a quick fix

**Comment by wahidrahim** [comment]
fixed issue about the mentioned badge aligntment:

image

**Comment by wahidrahim** [comment]
Using `TextOverflowEllipsis` to display name in the header as well:

image

**Review by remon-nashid — APPROVED** [review]
Looks good on my end!

**Pull request merged**
